// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH-WWmmkjq0e7QqeadJj1QuOBeLg7t1pQ',
    appId: '1:420553219400:android:539f7dc28f0e50c958a77d',
    messagingSenderId: '420553219400',
    projectId: 'testfb1237',
    databaseURL: 'https://testfb1237-default-rtdb.firebaseio.com',
    storageBucket: 'testfb1237.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5WAEpdxoOl5z79B_Fut3srY1r9nsexnM',
    appId: '1:420553219400:ios:2dbad17607435d3158a77d',
    messagingSenderId: '420553219400',
    projectId: 'testfb1237',
    databaseURL: 'https://testfb1237-default-rtdb.firebaseio.com',
    storageBucket: 'testfb1237.appspot.com',
    androidClientId: '420553219400-1lljfos43d9jidur96th1cn56p5uln0j.apps.googleusercontent.com',
    iosClientId: '420553219400-qrj2b2du76mne9sp8ovtali3gaobg7uj.apps.googleusercontent.com',
    iosBundleId: 'com.example.wealthwhiz',
  );
}
